[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[forms]]
  name = "offline-order"

[form-notifications]
  [[form-notifications.email]]
    form = "offline-order"
    to = "mivatextil@gmail.com"
    subject = "ВАЖЛИВО! Нове замовлення з сайту MIVA"
    template = """
ВАЖЛИВО! Нове замовлення на сайті MIVA:

=== ІНФОРМАЦІЯ ПРО КЛІЄНТА ===
ПІБ: {{ fullName }}
Телефон: {{ phone }}
Контакт (Email/Viber): {{ contact }}

=== ДОСТАВКА ===
Місто: {{ city }}
Відділення Нової Пошти: {{ branch }}

=== ЗАМОВЛЕННЯ ===
{{ orderSummary }}

=== ЗАГАЛЬНА СУМА ===
{{ totalSum }} грн

=== КОМЕНТАР КЛІЄНТА ===
{{ comments }}

---
⚠️ ВАЖЛИВО: Це замовлення потребує негайної обробки!
Відправлено з сайту MIVA (miva.com.ua)
Дата: {{ created_at }}
    """